CREATE TABLE PEDIDO (
    ID_PEDIDO INTEGER NOT NULL,
    DT_PEDIDO DATE NOT NULL,
    TOTAL_PEDIDO FLOAT NOT NULL,
    PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE PAGAMENTO (
    ID_PGTO INTEGER NOT NULL,
    PEDIDO_ID_PEDIDO INTEGER NOT NULL,
    NM_PGTO VARCHAR(255),
    PRIMARY KEY (ID_PGTO),
    FOREIGN KEY (PEDIDO_ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);
);